# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - ci
  - plugin
  - ruling

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]

exclude:

  - SLAVE: linux
    TEST: ruling

  - SLAVE: linux
    TEST: ci


  
  - SLAVE: windows
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: DEV

  - SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]


    
  - SLAVE: multicpu
    SQ_VERSION: DEV
    
  - SLAVE: multicpu
    SQ_VERSION: LATEST_RELEASE[6.7]

  - SLAVE: multicpu
    TEST: ci

  - SLAVE: multicpu
    TEST: plugin
